### ISSUE TITLE
Deno2

### ISSUE THREAD

**Issue by gedw99** [guest271314/native-messaging-piper#1]
Have you tried this with demo 2 ?

should work in theory too

**Comment by guest271314** [comment]
Yes. If you read the source code of `nm_piper.js` you'll notice the same file is designed to and does run using `node`, `deno`, and `bun` 
https://github.com/guest271314/native-messaging-piper/blob/df1b04778259198db9f8d04f5bde646c10c22c9e/nm_piper.js#L15-L42

**Comment by guest271314** [comment]
Just change the shebang line accordingly https://github.com/guest271314/native-messaging-piper/blob/df1b04778259198db9f8d04f5bde646c10c22c9e/nm_piper.js#L1-L3

**Comment by guest271314** [comment]
@gedw99 Do the above references to `nm_piper.js` answer your inquiry?

**Comment by guest271314** [comment]
The code already works using `deno` version 2 or greater.
